name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sinartimur-app:latest

      - name: Copy code to EC2 via SCP
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "./"
          target: "~/app"

  deploy:
    name: SSH Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull new image & restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            set -o allexport
            source /etc/environment
            set +o allexport

            cd ~/app

            chmod +x create-admin.sh
            chmod +x migrate.sh
            docker compose -f docker-compose.prod.yaml pull backend
            docker compose -f docker-compose.prod.yaml up -d --remove-orphans